apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/richkash/argocd-example-apps.git
    targetRevision: HEAD
    path: my-cluster-policies # <-- Points to the new directory

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
